### PR TITLE
horizontal list and text color

### PR DESCRIPTION
**Pull request by 97arushisharma**
Added few minute features. How to create a Horizontal List and to set Text Color.

### CODE REVIEW

**Comment by 0xadada** [comment]
@97arushisharma  If i fork this repo to @mirai-audio, i'd love to include this PR there. Would you be interested?

**Comment by charul97** [comment]
Ya, sure..

**Comment by 0xadada** [comment]
@97arushisharma what do you think? @charul97 

Here is the fork: https://github.com/mirai-audio/html5-kitchen-sink-test/pulls

**Comment by 97arushisharma** [comment]
No problem.

**Comment by cbracco** [comment]
Crazy that I am getting around to this now, but I added an example for background image in https://github.com/cbracco/html5-test-page/pull/36. 

Thanks @97arushisharma! 🎉

**Pull request closed without merging**
