### PR TITLE
Added a few elements

### PR DESCRIPTION
**Pull request by jKratzik**
address, details, embed, object, file input, datalist, keygen

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
Can you merge this PR?

**Comment by 0xadada** [comment]
@AurelioDeRosa @jKratzik   If i fork this repo to @mirai-audio, i'd love to include this PR there. Would you be interested?

**Comment by 0xadada** [comment]
@jKratzik @AurelioDeRosa here is a fork where i'd like to integrate these changes

https://github.com/mirai-audio/html5-kitchen-sink-test/

**Comment by cbracco** [comment]
I know it’s insane that I am doing this many years later, but here we are! Closing out, this one was merged in https://github.com/cbracco/html5-test-page/pull/35. Thanks @jKratzik!

**Pull request closed without merging**
